[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "anoma_vm_env"
resolver = "2"
version = "0.4.0"

[features]
default = ["ABCI"]

ABCI = [
  "anoma/ABCI",
]

ABCI-plus-plus = [
  "anoma/ABCI-plus-plus",
]

[dependencies]
anoma = {path = "../shared", default-features = false}
anoma_macros = {path = "../macros"}
borsh = "0.9.0"
hex = "0.4.3"